#pragma once
#include "SDLTools.h"
#define WINDOW_SIZE_X 500
#define WINDOW_SIZE_Y 500
#define WINDOW_POS_X SDL_WINDOWPOS_CENTERED
#define WINDOW_POS_Y SDL_WINDOWPOS_CENTERED
#define WINDOW_NAME "3D test"
#define WINDOW_FLAGS SDL_WINDOW_RESIZABLE